language: node_js
node_js:
  - "6"
install:
  - npm install coveralls
  - npm install
  - npm link
script: "npm run-script test-ci"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;"
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
